# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
- name: hashnode-user-with-posts-json
  uses: imbhargav5/hashnode-user-with-posts-json@v1.1
